version: 2
updates:
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: npm-check-updates
    versions:
    - 10.2.5
    - 11.1.1
    - 11.1.10
    - 11.1.4
    - 11.1.8
    - 11.1.9
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.3.0
    - 11.4.1
    - 11.5.1
    - 11.5.3
  - dependency-name: mathjax
    versions:
    - 3.1.2
    - 3.1.3
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
